all:
  hosts:
    wordpress:
      ansible_host: 192.168.56.10
      ansible_ssh_pass: vagrant
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/wordpress/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3

    database:
      ansible_host: 192.168.56.11
      ansible_ssh_pass: vagrant
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/mysql/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3
