---
- name: Baixando Wordpress
  ansible.builtin.get_url:
    url: https://br.wordpress.org/latest-pt_BR.tar.gz
    dest: /tmp/wordpress-6.2.2-pt_BR.tar.gz

- name: Descompacta o wordpress
  ansible.builtin.unarchive:
    src: /tmp/wordpress-6.2.2-pt_BR.tar.gz
    dest: /var/www/
    remote_src: true
  become: true

- name: Copiando o arquivo de configuração do Wordpress da máquina virtual
  ansible.builtin.copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: true

- name: Integrando Wordpress ao banco MySQL
  ansible.builtin.replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: '{{ item.regex }}'
    replace: '{{ item.value }}'
    backup: yes
  with_items:
    - { regex: 'nome_do_banco_de_dados_aqui', value: '{{ wp_db_name }}' }
    - { regex: 'nome_de_usuario_aqui', value: '{{ wp_username }}'}
    - { regex: 'senha_aqui', value: '{{ wp_password }}'}
    - { regex: 'localhost', value: '{{ wp_db_ip }}'}
  become: true

- name: Copiando arquivo de configuração exemplar para o Wordpress
  ansible.builtin.template:
    src: ../templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  become: true
  notify:
    - Reiniciar o serviço do Apache
