---
- name: Instalando pacotes e dependências
  ansible.builtin.apt:
    name:
      - php8.1
      - apache2
      - libapache2-mod-php8.1
      - php8.1-gd
      - php8.1-ssh2
      - python3-pip
      - php8.1-mysql
    state: latest
  become: true
